In [1]:
# An array is a structure that holds values grouped together, 
# like a 2 x 2 table of 2 rows and 2 columns. Arrays can also be **multidimensional**, such as a 2 x 2 x 2 array.
# Vectors are always one dimensional like a single row of data. On the other hand, an array can be multidimensional

In [2]:
#creating an array

In [3]:
#lets first create a vector of nine movies
movie_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
                  "Star Wars", "The Ring", "The Artist", "Jumanji")
movie_vector

[1] "Akira"      "Toy Story"  "Room"       "The Wave"   "Whiplash"  
[6] "Star Wars"  "The Ring"   "The Artist" "Jumanji"

In [4]:
movie_array <- array(movie_vector, dim = c(4,3))
movie_array

[,1]      [,2]       [,3]     
[1,] Akira     Whiplash   Jumanji  
[2,] Toy Story Star Wars  Akira    
[3,] Room      The Ring   Toy Story
[4,] The Wave  The Artist Room

In [5]:
# there were only 9 movie names, but the array was 4 x 3, the original vector doesn't have enough elements to 
# fill the entire array (that should have 3 x 4 = 12 elements).
# So R simply fills rest of the empty values by going back to the beginning of the vector and starting again

In [6]:
#access array elements

movie_array[1,2] #[row, column]
movie_array[1,]
movie_array[,2]

#get the dimension
dim(movie_array)

[1] "Whiplash"

[1] "Akira"    "Whiplash" "Jumanji"

[1] "Whiplash"   "Star Wars"  "The Ring"   "The Artist"

[1] 4 3

In [7]:
#do math on arrays
length_vector <- c(125, 81, 118, 81, 106, 121, 95, 100, 104)
length_array <- array(length_vector, dim = c(3,3))
length_array

[,1] [,2] [,3]
[1,] 125   81   95 
[2,]  81  106  100 
[3,] 118  121  104

In [8]:
length_array + 5

[,1] [,2] [,3]
[1,] 130   86  100 
[2,]  86  111  105 
[3,] 123  126  109

In [10]:
#logical conditions to subset arrays

mask_array <- length_array > 120
mask_array

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE FALSE
[3,] FALSE  TRUE FALSE

In [11]:
x_vector <- c("Akira", "Toy Story", "Room", "The Wave", "Whiplash",
              "Star Wars", "The Ring", "The Artist", "Jumanji")
x_array <- array(x_vector, dim = c(3,3))

x_array[mask_array]

[1] "Akira"     "Star Wars"

In [12]:
#matrix
# Matrices are a subtype of arrays. A matrix must have 2 dimensions,

In [13]:
movie_matrix <- matrix(movie_vector, nrow = 3, ncol = 3)
movie_matrix

[,1]      [,2]      [,3]      
[1,] Akira     The Wave  The Ring  
[2,] Toy Story Whiplash  The Artist
[3,] Room      Star Wars Jumanji

In [14]:
#accessing elements of a matrix
movie_matrix[1,1]
movie_matrix[2:3, 1:2]

[1] "Akira"

[,1]      [,2]     
[1,] Toy Story Whiplash 
[2,] Room      Star Wars

In [16]:
#concatenation
upcoming_movie <- c("Fast and Furious 8", "xXx: Return of Xander Cage", "Suicide Squad")
upcoming_movie

[1] "Fast and Furious 8"         "xXx: Return of Xander Cage"
[3] "Suicide Squad"

In [17]:
new_vector <- c(movie_vector, upcoming_movie)

In [18]:
new_vector

[1] "Akira"                      "Toy Story"                 
 [3] "Room"                       "The Wave"                  
 [5] "Whiplash"                   "Star Wars"                 
 [7] "The Ring"                   "The Artist"                
 [9] "Jumanji"                    "Fast and Furious 8"        
[11] "xXx: Return of Xander Cage" "Suicide Squad"