In [1]:
#Everything that you manipulate in R is called an object.
#One of the attributes in objects is called the class of the object.
# The class of an object is the data type of this object.
# The various classes (data types) of objects in R are important
# The most common classes (data types) of objects in R are:

# numeric (real numbers)
# character
# integer
# logical (True/False)
# complex


In [2]:
# create a variable from the average rating of some movies and then find which data types they belong to:
movie_rating <- c(8.3, 5.2, 9.3, 8.0) # create a vector from average ratings 
movie_rating # print the variable

class(movie_rating) # show the variable's data type

[1] 8.3 5.2 9.3 8.0

[1] "numeric"

In [3]:
# A vector can only contain objects of the same class. However, a list can have different data types.
#decimal values are called numerics

average_rating <- 8.3       # assign a decimal value
average_rating 

[1] 8.3

In [4]:
class(average_rating)      

[1] "numeric"

In [5]:
#a character object represents string values
movies <-c("Toy Story", "Akira", "The Breakfast Club", "The Artist")
movies
class(movies)

[1] "Toy Story"          "Akira"              "The Breakfast Club"
[4] "The Artist"

[1] "character"

In [7]:
#if numbers and texts are combined in a vector, everything is converted to the class character

combined <- c("Toy Story", 1995, "Akira", 1998)
combined
class(combined)

[1] "Toy Story" "1995"      "Akira"     "1998"

[1] "character"

In [8]:
#numbers are saved as numerics by default

movie_length <- c(80, 110, 90, 80) # create a vector from movie length
movie_length # print the variable
class(movie_length)


[1]  80 110  90  80

[1] "numeric"

In [9]:
#integers

age_restriction <- c(12, 10, 18, 18) # create a vector from age restriction
age_restriction # print the vector

class(age_restriction)



[1] 12 10 18 18

[1] "numeric"

In [10]:
#convert to integer

integer_vector <- as.integer(age_restriction)
class(integer_vector)

[1] "integer"

In [11]:
#logical class

logical_vector <- c(T,F,F,T,T) # creating the vector
class(logical_vector)

[1] "logical"

In [12]:
#logical values are created by comparison

length_Akira <- 125
length_ToyStory <- 81

#comparison
x <- length_ToyStory > length_Akira      # is ToyStory larger than akira? 
x              

[1] FALSE

In [13]:
x <- length_Akira > length_ToyStory # is akira larger than ToyStory?               
x # print the logical value

[1] TRUE

In [15]:
#variable obtained from comparison is logical in nature
class(x)       # print the class name of x

[1] "logical"

In [16]:
#complex numbers
# A complex number is a number that can be expressed in the form a + bi,
# where a and b are real numbers and i is the imaginary unit.

z = 8 + 6i     # create a complex number 
z

[1] 8+6i

In [17]:
class(z)

[1] "complex"

In [18]:
#convert class into a different data type

year <- as.character(1995) # convert integer into character data type
year                    # print the value of year in character data type

[1] "1995"

In [19]:
#creating an integer
Length_ToyStory <- 81
class(81)

[1] "numeric"

In [20]:
length_ToyStory <- as.integer(81) 
class(length_ToyStory)       # print the class name of length_ToyStory

[1] "integer"

In [21]:
#Class & Mode
# For a simple vector, the class and mode of the vector are the same thing:
# the data type of the values inside the vector (character, numeric, integer, etc). 
# However, in some of other objects such as matrix, array, data frame, and list, 
# class and mode means different things.

#finding class and mode
movies <- c("Toy Story", "Akira", "The Breakfast Club", "The Artist") # creating two vectors
genre <- c("Animation/Adventure/Comedy", "Animation/Adventure/Comedy", "Comedy/Drama", "Comedy/Drama")

class(movies)
mode(movies)

[1] "character"

[1] "character"

In [22]:
movies_genre <- cbind(movies, genre)
movies_genre 

movies             genre                     
[1,] Toy Story          Animation/Adventure/Comedy
[2,] Akira              Animation/Adventure/Comedy
[3,] The Breakfast Club Comedy/Drama              
[4,] The Artist         Comedy/Drama

In [23]:
class(movies_genre)

mode(movies_genre)

[1] "matrix"

[1] "character"

In [24]:
##Arrays
#arrays can store matrices as elements

sample_array <- array(1:12, dim = c(3, 2, 2)) # create an array with dimensions 3 x 2 x 2 
sample_array
class(sample_array)
mode(sample_array)

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

[1] "array"

[1] "numeric"

In [25]:
#Data Frame
#are similar to arrays but allow to associate each row and each column with a name.

Name <- c("Toy Story", "Akira", "The Breakfast Club", "The Artist")
Year <- c(1995, 1998, 1985, 2011)
Length <- c(81, 125, 97, 100)
RowNames = c("Movie 1", "Movie 2", "Movie 3", "Movie 4")

sample_DataFrame <- data.frame(Name, Year, Length, row.names=RowNames) 
sample_DataFrame

class(sample_DataFrame)

Name               Year Length
Movie 1 Toy Story          1995  81   
Movie 2 Akira              1998 125   
Movie 3 The Breakfast Club 1985  97   
Movie 4 The Artist         2011 100

[1] "data.frame"

In [27]:
##Lists: can contain multiple data types
sample_list = list("Star Wars", 8.7, TRUE)
sample_list

class(sample_list)

[[1]]
[1] "Star Wars"

[[2]]
[1] 8.7

[[3]]
[1] TRUE

[1] "list"

In [28]:
#Attributes -- objects can have one or more attributes
#you can change any individual attribute of an object with the attr() function

z <- c(8.3, 8.1, 7.9, 8, 30, 10.4, 1, 15)
z
attr(z, "dim") <- c(4,2)
z


[1]  8.3  8.1  7.9  8.0 30.0 10.4  1.0 15.0

[,1] [,2]
[1,] 8.3  30.0
[2,] 8.1  10.4
[3,] 7.9   1.0
[4,] 8.0  15.0

In [29]:
#find the class and mode of the matrix
class(z)
mode(z)

[1] "matrix"

[1] "numeric"

In [ ]:
##thank you....
#more code to follow!!!